[package]
name = "ds210_final"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv ="1.1"
rulinalg="0.4.2"
petgraph = "0.6.0"
rand = "0.8.5"